name: capstone_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  file_picker: ^5.3.2
  http: ^1.0.0
  auto_route: ^7.4.0
  logger: ^1.4.0
  localstorage: ^4.0.1+4
  flutter_html: ^3.0.0-beta.2
  webview_flutter: ^4.2.1
  webview_flutter_web: ^0.2.2+1
  percent_indicator: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator:
  build_runner:


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_image/logo.png
    - assets/landing/

#  fonts:
#    - family: Literata
#      fonts:
#        - asset: fonts/Literata/LiterataRegular-jMG7.ttf
#        - asset: fonts/Literata/LiterataItalic-VjLV.ttf
#          style: italic
#        - asset: fonts/Literata/LiterataBold-AOjm.ttf
#          weight: 900
#        - asset: fonts/Literata/LiterataBold-AOjm.ttf
#          style: bold
