name: capstone_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_slider_drawer: ^2.1.3 # TODO: Maybe you can delete it
  file_picker: ^5.3.2
  http: ^1.0.0
  auto_route: ^7.4.0
  logger: ^1.4.0
  localstorage: ^4.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator:
  build_runner:


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo_image/logo.png

  fonts:
    - family: Literata
      fonts:
        - asset: fonts/Literata/LiterataRegular-jMG7.ttf
        - asset: fonts/Literata/LiterataItalic-VjLV.ttf
          style: italic
        - asset: fonts/Literata/LiterataBold-AOjm.ttf
          weight: 900
#        - asset: fonts/Literata/LiterataBold-AOjm.ttf
#          style: bold
